---
- name: "install ufw"
  apt:
    package: ufw
    update_cache: yes
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"
  retries: "{{ remote_package_retries }}"
  register: apt_result
  until: apt_result is succeeded
  tags:
    - firewall

- name: "enable logging"
  ufw:
    logging: "{{ firewall_logging }}"
  tags:
    - firewall

- name: "allow ssh connections"
  ufw:
    rule: allow
    port: ssh
  tags:
    - firewall

- name: "allow various connections"
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items: "{{ firewall_allowed_ports }}"
  tags:
    - firewall

- name: "allow incoming access from ip"
  ufw:
    rule: allow
    from_ip: "{{ item }}"
  with_items: "{{ firewall_allowed_hosts }}"
  tags:
    - firewall

- name: "custom rules"
  ufw:
    rule: "{{ item.rule | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default('any') }}"
    from_port: "{{ item.from_port | default(omit) }}"
    interface:  "{{ item.interface | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    to_ip: "{{ item.to_ip | default('any') }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items: "{{ firewall_custom_rules }}"
  tags:
    - firewall

- name: "deny all other connections and enable firewall"
  ufw:
    state: enabled
    direction: incoming
    policy: deny
  tags:
    - firewall
