- name: "Install ufw"
  apt:
    package: ufw
    update_cache: yes
    state: present
  tags:
    - apt
    - firewall
    - network

- name: "Allow logging"
  ufw:
    logging: 'on'
  tags:
    - firewall
    - network

- name: "Allow ssh connections"
  ufw:
    rule: allow
    port: ssh
  tags:
    - firewall
    - network

- name: "Allow various connections"
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items: '{{ allowed_ports }}'
  tags:
    - firewall
    - network

- name: "Allow incoming access from speciefied ips"
  ufw:
    rule: allow
    from_ip: "{{ hostvars[item].specified_ip }}"
  with_items: '{{ groups.all }}'
  tags:
    - firewall
    - network

- name: "Deny all other connections and enable firewall"
  ufw:
    state: enabled
    policy: deny
  tags:
    - firewall
    - network

- name: "Log only to ufw.log"
  template:
    src: "20-ufw.conf.j2"
    dest: "/etc/rsyslog.d/20-ufw.conf"
    mode: 0644
    owner: root
    group: root
  notify: restart rsyslog
  tags:
    - firewall
    - network
