---
- name: "install ufw"
  apt:
    package: ufw
    update_cache: yes
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"
  tags:
    - firewall

- name: "enable logging"
  ufw:
    logging: "{{ firewall_enable_log }}"
  tags:
    - firewall

- name: "allow ssh connections"
  ufw:
    rule: allow
    port: ssh
  tags:
    - firewall

- name: "allow various connections"
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items: "{{ firewall_allowed_ports }}"
  tags:
    - firewall

- name: "allow incoming access from ip"
  ufw:
    rule: allow
    from_ip: "{{ item }}"
  with_items: "{{ firewall_allowed_hosts }}"
  tags:
    - firewall

- name: "deny all other connections and enable firewall"
  ufw:
    state: enabled
    policy: deny
  tags:
    - firewall
